/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  // tutorialSidebar: [
  //   'Development',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
  developmentSidebar: [
    {
      type: 'doc',
      id: 'Development/EEPROM Usage/index',
      label: 'EEPROM Usage',
    },
    {
      type: 'category',
      label: 'SD',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'statInfo',
          link: {type: 'doc', id: 'Development/SD Card/statInfo/index'},
          items: [
            'Development/SD Card/statInfo/batvolt.txt/index',
            'Development/SD Card/statInfo/errorlog.txt/index',
          ]
        },
        {
          type: 'category',
          label: 'statOpts',
          link: {type: 'doc', id: 'Development/SD Card/statOpts/index'},
          items: [
            'Development/SD Card/statOpts/statName.txt/index',
            'Development/SD Card/statOpts/time.txt/index',
            // 'Development/SD Card/statOpts/index',
          ],
        },
      ],
    },
    {
      type: 'doc',
      id: 'Development/Task List/index',
      label: 'Task List',
    },
  ],

  diySidebar: [
    {
      type: 'doc',
      id: 'DIY/Build Dependencies/index',
      label: 'Build Dependencies',
    },
    {
      type: 'doc',
      id: 'DIY/Supported Platforms/index',
      label: 'Supported Platforms',
    },
  ],
};

module.exports = sidebars;
